import type { LucideIcon } from "lucide-react"
import {
  Clapperboard,
  Newspaper,
  Film,
  FolderOpen,
  FileText,
  Megaphone,
  Building2,
  ShieldCheck,
  Zap,
  ListChecks,
  MessageSquare,
  Trophy,
  CircleHelp,
  Mail,
  CreditCard,
  Image,
  Target,
  Lightbulb,
  BarChart3,
  Phone,
  MapPin,
  Clock,
  Share2,
  Inbox,
  Search,
  Grid3X3,
  Heading,
} from "lucide-react"

export type PageAdminId = "page-home" | "page-platforms" | "page-about" | "page-contact"

export type PageSectionLink = {
  id: string
  icon: LucideIcon
  titleAr: string
  titleEn: string
  descAr: string
  descEn: string
  adminTab: string
  /** أنماط حقول المحتوى النصي لهذا القسم */
  contentKeys?: string
}

export type PageAdminConfig = {
  id: PageAdminId
  titleAr: string
  titleEn: string
  descAr: string
  descEn: string
  previewHash: string
  sections: PageSectionLink[]
}

export const PAGE_ADMIN_CONFIG: Record<PageAdminId, PageAdminConfig> = {
  "page-home": {
    id: "page-home",
    titleAr: "الصفحة الرئيسية",
    titleEn: "Home Page",
    descAr: "إدارة جميع أقسام الصفحة الرئيسية: الهيدر، المنصات، الشريط الإخباري، والمحتوى.",
    descEn: "Manage all homepage sections: hero, platforms, news ticker, and content blocks.",
    previewHash: "#/",
    sections: [
      {
        id: "hero",
        icon: Clapperboard,
        titleAr: "الهيدر والبنر الرئيسي",
        titleEn: "Hero & main banner",
        descAr: "العنوان، الوصف، الصور، الفيديو، الشعار، وأزرار الدعوة.",
        descEn: "Title, subtitle, slides, video, logo, and call-to-action buttons.",
        adminTab: "home-banners",
      },
      {
        id: "hero-typography",
        icon: Heading,
        titleAr: "خطوط وألوان الهيدر",
        titleEn: "Hero typography",
        descAr: "نصوص وألوان وخطوط هيدر الصفحة الرئيسية.",
        descEn: "Home hero texts, colors, and fonts.",
        adminTab: "page-headers",
      },
      {
        id: "news-ticker",
        icon: Newspaper,
        titleAr: "الشريط الإخباري",
        titleEn: "News ticker",
        descAr: "نصوص الأخبار المتحركة والألوان والخط.",
        descEn: "Scrolling headlines, colors, and typography.",
        adminTab: "news-ticker",
      },
      {
        id: "platforms-grid",
        icon: FolderOpen,
        titleAr: "شبكة المنصات (12 منصة)",
        titleEn: "Platforms grid (12 modules)",
        descAr: "أسماء وأوصاف وصور بطاقات المنصات الـ12.",
        descEn: "Names, descriptions, and images for all 12 platform cards.",
        adminTab: "projects",
      },
      {
        id: "image-strip",
        icon: Film,
        titleAr: "شريط الصور",
        titleEn: "Image strip",
        descAr: "الشريط المتحرك أسفل الهيدر والصور الإضافية.",
        descEn: "Animated strip below hero and extra images.",
        adminTab: "image-strip",
      },
      {
        id: "payment-methods",
        icon: CreditCard,
        titleAr: "طرق الدفع",
        titleEn: "Payment methods",
        descAr: "عرض شعارات وسائل الدفع في الصفحة.",
        descEn: "Payment method logos shown on the homepage.",
        adminTab: "home-payments",
        contentKeys: "home.payments_*",
      },
      {
        id: "marquee",
        icon: Megaphone,
        titleAr: "الشريط المتحرك",
        titleEn: "Marquee banner",
        descAr: "النصوص المتحركة أسفل قسم الدفع.",
        descEn: "Scrolling stats and highlights strip.",
        adminTab: "home-marquee",
        contentKeys: "home.marquee_*",
      },
      {
        id: "about-brief",
        icon: Building2,
        titleAr: "نبذة مختصرة عن CIAR",
        titleEn: "About brief",
        descAr: "قسم التعريف المختصر في الصفحة الرئيسية.",
        descEn: "Short company intro block on the homepage.",
        adminTab: "home-about-brief",
        contentKeys: "home.about_*",
      },
      {
        id: "trust-badges",
        icon: ShieldCheck,
        titleAr: "شارات الثقة",
        titleEn: "Trust badges",
        descAr: "SSL، GDPR، الدعم، وقت التشغيل.",
        descEn: "SSL, GDPR, support, and uptime badges.",
        adminTab: "home-trust-badges",
        contentKeys: "home.badge_*",
      },
      {
        id: "services-grid",
        icon: Zap,
        titleAr: "12 منصة متكاملة",
        titleEn: "Integrated platforms grid",
        descAr: "عناوين ووصف قسم المنصات (يُحمّل تلقائياً من المنصات).",
        descEn: "Section titles; platform cards load from modules API.",
        adminTab: "home-services",
        contentKeys: "home.services_*",
      },
      {
        id: "how-it-works",
        icon: ListChecks,
        titleAr: "كيف تعمل المنصة",
        titleEn: "How it works",
        descAr: "الخطوات الأربع وشرحها.",
        descEn: "Four-step process and descriptions.",
        adminTab: "home-how-it-works",
        contentKeys: "home.how_*",
      },
      {
        id: "testimonials",
        icon: MessageSquare,
        titleAr: "آراء العملاء",
        titleEn: "Testimonials",
        descAr: "اقتباسات وأسماء العملاء.",
        descEn: "Customer quotes and names.",
        adminTab: "home-testimonials",
        contentKeys: "home.testimonial_*",
      },
      {
        id: "awards",
        icon: Trophy,
        titleAr: "الجوائز والاعتمادات",
        titleEn: "Awards banner",
        descAr: "شريط الجوائز والشهادات.",
        descEn: "Awards and certifications strip.",
        adminTab: "home-awards",
        contentKeys: "home.awards_*",
      },
      {
        id: "news-updates",
        icon: Newspaper,
        titleAr: "الأخبار والتحديثات",
        titleEn: "News updates",
        descAr: "آخر الأخبار والمقالات.",
        descEn: "Latest news and updates section.",
        adminTab: "home-news",
        contentKeys: "home.news_*",
      },
      {
        id: "faq",
        icon: CircleHelp,
        titleAr: "الأسئلة الشائعة",
        titleEn: "FAQ",
        descAr: "أسئلة وأجوبة متكررة.",
        descEn: "Frequently asked questions.",
        adminTab: "home-faq",
        contentKeys: "home.faq_*",
      },
      {
        id: "newsletter",
        icon: Mail,
        titleAr: "اشتراك النشرة البريدية",
        titleEn: "Newsletter CTA",
        descAr: "دعوة الاشتراك في النشرة.",
        descEn: "Newsletter signup call-to-action.",
        adminTab: "home-newsletter",
        contentKeys: "home.newsletter_*",
      },
      {
        id: "backgrounds",
        icon: Image,
        titleAr: "خلفيات الصفحة",
        titleEn: "Page backgrounds",
        descAr: "صور الخلفية للهيدر والأقسام.",
        descEn: "Hero and section background images.",
        adminTab: "backgrounds",
      },
    ],
  },
  "page-platforms": {
    id: "page-platforms",
    titleAr: "صفحة منصاتنا",
    titleEn: "Our Platforms Page",
    descAr: "إدارة عنوان الصفحة، الإحصاءات، وبطاقات المنصات المعروضة للزوار.",
    descEn: "Manage page header, stats, and platform cards shown to visitors.",
    previewHash: "#/projects",
    sections: [
      {
        id: "header-text",
        icon: FileText,
        titleAr: "عنوان ووصف الصفحة",
        titleEn: "Page title & subtitle",
        descAr: "العنوان الرئيسي والنص التمهيدي.",
        descEn: "Main heading and intro text.",
        adminTab: "page-headers",
        contentKeys: "projects.title, projects.subtitle",
      },
      {
        id: "header-bg",
        icon: Image,
        titleAr: "صورة خلفية الهيدر",
        titleEn: "Header background",
        descAr: "خلفية قسم الهيدر في صفحة المنصات.",
        descEn: "Hero header background for platforms page.",
        adminTab: "backgrounds",
      },
      {
        id: "stats",
        icon: BarChart3,
        titleAr: "بطاقات الإحصاءات",
        titleEn: "Stats cards",
        descAr: "عدد المنصات، المشاهدات، المميزة، التصنيفات.",
        descEn: "Platform count, views, featured, categories labels.",
        adminTab: "platforms-stats",
        contentKeys: "projects.total_projects, projects.featured, hero.stat_*",
      },
      {
        id: "platform-cards",
        icon: FolderOpen,
        titleAr: "بطاقات المنصات",
        titleEn: "Platform cards",
        descAr: "إضافة وتعديل ونشر المنصات الـ12.",
        descEn: "Add, edit, and publish all platform entries.",
        adminTab: "projects",
      },
      {
        id: "search-filter",
        icon: Search,
        titleAr: "البحث والتصنيفات",
        titleEn: "Search & filters",
        descAr: "نصوص البحث والتصنيفات والفرز.",
        descEn: "Search placeholder and category filter labels.",
        adminTab: "platforms-search",
        contentKeys: "projects.search_*, projects.all, projects.no_results, projects.no_results_desc, common.search",
      },
      {
        id: "grid-layout",
        icon: Grid3X3,
        titleAr: "عرض الشبكة",
        titleEn: "Grid display",
        descAr: "بطاقات المنصات تُعرض تلقائياً من المنصات المنشورة.",
        descEn: "Cards render from published platform modules.",
        adminTab: "projects",
      },
    ],
  },
  "page-about": {
    id: "page-about",
    titleAr: "صفحة عن CIAR",
    titleEn: "About CIAR Page",
    descAr: "إدارة محتوى صفحة «من نحن»: الرؤية، الرسالة، القيم، والإحصاءات.",
    descEn: "Manage About page: mission, vision, values, stats, and company intro.",
    previewHash: "#/about",
    sections: [
      {
        id: "hero-text",
        icon: FileText,
        titleAr: "عنوان الهيدر",
        titleEn: "Hero header",
        descAr: "الشارة، العنوان، والوصف التمهيدي.",
        descEn: "Badge, title, and subtitle.",
        adminTab: "page-headers",
        contentKeys: "about.badge, about.title_*, about.subtitle",
      },
      {
        id: "hero-bg",
        icon: Image,
        titleAr: "صورة خلفية الهيدر",
        titleEn: "Header background",
        descAr: "خلفية قسم الهيدر في صفحة من نحن.",
        descEn: "About page hero background image.",
        adminTab: "backgrounds",
      },
      {
        id: "mission",
        icon: Target,
        titleAr: "رسالتنا",
        titleEn: "Mission",
        descAr: "عنوان ونص الرسالة.",
        descEn: "Mission title and body text.",
        adminTab: "about-mission",
        contentKeys: "about.mission_*",
      },
      {
        id: "vision",
        icon: Lightbulb,
        titleAr: "رؤيتنا",
        titleEn: "Vision",
        descAr: "عنوان ونص الرؤية.",
        descEn: "Vision title and body text.",
        adminTab: "about-vision",
        contentKeys: "about.vision_*",
      },
      {
        id: "company-intro",
        icon: Building2,
        titleAr: "النص التعريفي (تحت قيمنا)",
        titleEn: "Company intro (under values)",
        descAr: "النبذة الطويلة عن الشركة بالعربية والإنجليزية.",
        descEn: "Long company description in Arabic and English.",
        adminTab: "about-content",
      },
      {
        id: "values",
        icon: ShieldCheck,
        titleAr: "قيمنا (6 بطاقات)",
        titleEn: "Our values (6 cards)",
        descAr: "عناوين ووصف كل قيمة.",
        descEn: "Titles and descriptions for each value card.",
        adminTab: "about-values",
        contentKeys: "about.values_*, about.value_*",
      },
      {
        id: "stats",
        icon: BarChart3,
        titleAr: "إحصاءات الشركة",
        titleEn: "Company stats",
        descAr: "الأرقام والتسميات (منتجات، مستخدمون، …).",
        descEn: "Figures and labels (products, users, uptime, …).",
        adminTab: "about-stats",
        contentKeys: "about.stat_*",
      },
    ],
  },
  "page-contact": {
    id: "page-contact",
    titleAr: "صفحة تواصل",
    titleEn: "Contact Page",
    descAr: "إدارة معلومات التواصل، نموذج الرسائل، وروابط السوشial.",
    descEn: "Manage contact info, form labels, social links, and inbox.",
    previewHash: "#/contact",
    sections: [
      {
        id: "hero-text",
        icon: FileText,
        titleAr: "عنوان الهيدر",
        titleEn: "Hero header",
        descAr: "العنوان والوصف في أعلى صفحة التواصل.",
        descEn: "Title and subtitle at top of contact page.",
        adminTab: "page-headers",
        contentKeys: "contact.badge, contact.title_*, contact.subtitle",
      },
      {
        id: "hero-bg",
        icon: Image,
        titleAr: "صورة خلفية الهيدر",
        titleEn: "Header background",
        descAr: "خلفية قسم الهيدر في صفحة التواصل.",
        descEn: "Contact page hero background.",
        adminTab: "backgrounds",
      },
      {
        id: "contact-details",
        icon: Phone,
        titleAr: "بيانات التواصل",
        titleEn: "Contact details",
        descAr: "البريد، الهاتف، العنوان، وساعات العمل.",
        descEn: "Email, phone, address, and working hours.",
        adminTab: "settings",
      },
      {
        id: "form-labels",
        icon: Mail,
        titleAr: "نموذج الرسالة",
        titleEn: "Contact form",
        descAr: "تسميات الحقول، الأزرار، ورسائل التحقق.",
        descEn: "Field labels, buttons, and validation messages.",
        adminTab: "contact-form",
        contentKeys: "contact.name_*, contact.email_*, contact.phone_*, contact.subject_*, contact.message_*, contact.send, contact.sending, contact.success, contact.error, contact.validation_error",
      },
      {
        id: "social-links",
        icon: Share2,
        titleAr: "روابط التواصل الاجتماعي",
        titleEn: "Social links",
        descAr: "واتساب، تيليغرام، فيسبوك، إنستغرام، وغيرها.",
        descEn: "WhatsApp, Telegram, Facebook, Instagram, etc.",
        adminTab: "settings",
      },
      {
        id: "inbox",
        icon: Inbox,
        titleAr: "صندوق الرسائل الواردة",
        titleEn: "Messages inbox",
        descAr: "قراءة والرد على رسائل الزوار.",
        descEn: "Read and manage visitor submissions.",
        adminTab: "contacts",
      },
      {
        id: "map",
        icon: MapPin,
        titleAr: "الموقع على الخريطة",
        titleEn: "Map location",
        descAr: "عنوان المكتب المعروض في الصفحة.",
        descEn: "Office address shown on the contact page.",
        adminTab: "settings",
      },
      {
        id: "hours",
        icon: Clock,
        titleAr: "ساعات العمل",
        titleEn: "Working hours",
        descAr: "أوقات الدوام والرد على الرسائل.",
        descEn: "Business hours displayed to visitors.",
        adminTab: "contact-hours",
        contentKeys: "contact.response_*",
      },
    ],
  },
}

export const PAGE_ADMIN_IDS = Object.keys(PAGE_ADMIN_CONFIG) as PageAdminId[]

export function isPageAdminId(tab: string): tab is PageAdminId {
  return PAGE_ADMIN_IDS.includes(tab as PageAdminId)
}
